# Lauren Holley
# 1861058
cup_lemon = int(input("Enter amount of lemon juice (in cups):"))
print()
cup_water = int(input("Enter amount of water (in cups):"))
print()
cup_agave = float(input("Enter amount of agave nectar (in cups):"))
print()
amount_servings = int(input("How many servings does this make?"))
print()
print()
print("Lemonade ingredients - yields", '{:.2f}'.format(amount_servings), "servings")
print('{:.2f}'.format(cup_lemon), "cup(s) lemon juice")
print('{:.2f}'.format(cup_water), "cup(s) water")
print('{:.2f}'.format(cup_agave), "cup(s) agave nectar")
print()
req_servings = int(input("How many servings would you like to make?"))
print()
print()
div_servings = req_servings / amount_servings
print("Lemonade ingredients - yields", '{:.2f}'.format(req_servings), "servings")
print('{:.2f}'.format(cup_lemon * div_servings), "cup(s) lemon juice")
print('{:.2f}'.format(cup_water * div_servings), "cup(s) water")
print('{:.2f}'.format(cup_agave * div_servings), "cup(s) agave nectar")
print()
print("Lemonade ingredients - yields", '{:.2f}'.format(req_servings), "servings")
print('{:.2f}'.format((cup_lemon * div_servings)/16), "gallon(s) lemon juice")
print('{:.2f}'.format((cup_water * div_servings)/16), "gallon(s) water")
print('{:.2f}'.format((cup_agave * div_servings)/ 16), "gallon(s) agave nectar")